// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: ordenCliente.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Solicitamos un pedido
type SolicitudPedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//id-paquete tipo nombre valor origen destino
	IdPaquete string `protobuf:"bytes,1,opt,name=idPaquete,proto3" json:"idPaquete,omitempty"`
	Tipo      string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre    string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor     string `protobuf:"bytes,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen    string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino   string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *SolicitudPedido) Reset() {
	*x = SolicitudPedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordenCliente_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudPedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudPedido) ProtoMessage() {}

func (x *SolicitudPedido) ProtoReflect() protoreflect.Message {
	mi := &file_ordenCliente_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudPedido.ProtoReflect.Descriptor instead.
func (*SolicitudPedido) Descriptor() ([]byte, []int) {
	return file_ordenCliente_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudPedido) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *SolicitudPedido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *SolicitudPedido) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *SolicitudPedido) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *SolicitudPedido) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *SolicitudPedido) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type RespuestaPedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//respuesta al solicitar un pedido
	CodigoSeguimiento string `protobuf:"bytes,1,opt,name=codigoSeguimiento,proto3" json:"codigoSeguimiento,omitempty"`
}

func (x *RespuestaPedido) Reset() {
	*x = RespuestaPedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordenCliente_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaPedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaPedido) ProtoMessage() {}

func (x *RespuestaPedido) ProtoReflect() protoreflect.Message {
	mi := &file_ordenCliente_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaPedido.ProtoReflect.Descriptor instead.
func (*RespuestaPedido) Descriptor() ([]byte, []int) {
	return file_ordenCliente_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaPedido) GetCodigoSeguimiento() string {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return ""
}

//Solicitamos un seguimiento
type SolicitudSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//id-paquete tipo nombre valor origen destino
	CodigoSeguimiento string `protobuf:"bytes,1,opt,name=codigoSeguimiento,proto3" json:"codigoSeguimiento,omitempty"`
}

func (x *SolicitudSeguimiento) Reset() {
	*x = SolicitudSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordenCliente_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudSeguimiento) ProtoMessage() {}

func (x *SolicitudSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_ordenCliente_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudSeguimiento.ProtoReflect.Descriptor instead.
func (*SolicitudSeguimiento) Descriptor() ([]byte, []int) {
	return file_ordenCliente_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudSeguimiento) GetCodigoSeguimiento() string {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return ""
}

//Respuesta del estado
type RespuestaSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//id-paquete tipo nombre valor origen destino
	EstadoPedido string `protobuf:"bytes,1,opt,name=estadoPedido,proto3" json:"estadoPedido,omitempty"`
}

func (x *RespuestaSeguimiento) Reset() {
	*x = RespuestaSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordenCliente_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaSeguimiento) ProtoMessage() {}

func (x *RespuestaSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_ordenCliente_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaSeguimiento.ProtoReflect.Descriptor instead.
func (*RespuestaSeguimiento) Descriptor() ([]byte, []int) {
	return file_ordenCliente_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaSeguimiento) GetEstadoPedido() string {
	if x != nil {
		return x.EstadoPedido
	}
	return ""
}

var File_ordenCliente_proto protoreflect.FileDescriptor

var file_ordenCliente_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x73,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f,
	0x22, 0x3f, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x50, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x22, 0x44, 0x0a, 0x14, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x53, 0x65,
	0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x64,
	0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x32, 0x92, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x50, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1a,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x53,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ordenCliente_proto_rawDescOnce sync.Once
	file_ordenCliente_proto_rawDescData = file_ordenCliente_proto_rawDesc
)

func file_ordenCliente_proto_rawDescGZIP() []byte {
	file_ordenCliente_proto_rawDescOnce.Do(func() {
		file_ordenCliente_proto_rawDescData = protoimpl.X.CompressGZIP(file_ordenCliente_proto_rawDescData)
	})
	return file_ordenCliente_proto_rawDescData
}

var file_ordenCliente_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ordenCliente_proto_goTypes = []interface{}{
	(*SolicitudPedido)(nil),      // 0: grpc.solicitudPedido
	(*RespuestaPedido)(nil),      // 1: grpc.respuestaPedido
	(*SolicitudSeguimiento)(nil), // 2: grpc.solicitudSeguimiento
	(*RespuestaSeguimiento)(nil), // 3: grpc.respuestaSeguimiento
}
var file_ordenCliente_proto_depIdxs = []int32{
	0, // 0: grpc.Greeter.GetPedido:input_type -> grpc.solicitudPedido
	2, // 1: grpc.Greeter.GetSeguimiento:input_type -> grpc.solicitudSeguimiento
	1, // 2: grpc.Greeter.GetPedido:output_type -> grpc.respuestaPedido
	3, // 3: grpc.Greeter.GetSeguimiento:output_type -> grpc.respuestaSeguimiento
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ordenCliente_proto_init() }
func file_ordenCliente_proto_init() {
	if File_ordenCliente_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ordenCliente_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudPedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ordenCliente_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaPedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ordenCliente_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ordenCliente_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ordenCliente_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordenCliente_proto_goTypes,
		DependencyIndexes: file_ordenCliente_proto_depIdxs,
		MessageInfos:      file_ordenCliente_proto_msgTypes,
	}.Build()
	File_ordenCliente_proto = out.File
	file_ordenCliente_proto_rawDesc = nil
	file_ordenCliente_proto_goTypes = nil
	file_ordenCliente_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	//funciones get
	GetPedido(ctx context.Context, in *SolicitudPedido, opts ...grpc.CallOption) (*RespuestaPedido, error)
	GetSeguimiento(ctx context.Context, in *SolicitudSeguimiento, opts ...grpc.CallOption) (*RespuestaSeguimiento, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetPedido(ctx context.Context, in *SolicitudPedido, opts ...grpc.CallOption) (*RespuestaPedido, error) {
	out := new(RespuestaPedido)
	err := c.cc.Invoke(ctx, "/grpc.Greeter/GetPedido", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetSeguimiento(ctx context.Context, in *SolicitudSeguimiento, opts ...grpc.CallOption) (*RespuestaSeguimiento, error) {
	out := new(RespuestaSeguimiento)
	err := c.cc.Invoke(ctx, "/grpc.Greeter/GetSeguimiento", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	//funciones get
	GetPedido(context.Context, *SolicitudPedido) (*RespuestaPedido, error)
	GetSeguimiento(context.Context, *SolicitudSeguimiento) (*RespuestaSeguimiento, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetPedido(context.Context, *SolicitudPedido) (*RespuestaPedido, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPedido not implemented")
}
func (*UnimplementedGreeterServer) GetSeguimiento(context.Context, *SolicitudSeguimiento) (*RespuestaSeguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeguimiento not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudPedido)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Greeter/GetPedido",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetPedido(ctx, req.(*SolicitudPedido))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetSeguimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudSeguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetSeguimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Greeter/GetSeguimiento",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetSeguimiento(ctx, req.(*SolicitudSeguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPedido",
			Handler:    _Greeter_GetPedido_Handler,
		},
		{
			MethodName: "GetSeguimiento",
			Handler:    _Greeter_GetSeguimiento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordenCliente.proto",
}
